/**
 * Type Definitions for the Kanban Application
 * Central location for all TypeScript type and interface definitions
 * Used throughout the app for type safety and autocomplete support
 */

/**
 * Task: Main data model for Kanban tasks
 * @property id - Unique identifier for the task (auto-generated by backend)
 * @property title - Task name/headline
 * @property description - Detailed task information
 * @property column - Current position on the board (which column the task is in)
 * @property priority - Task importance level: HIGH, MEDIUM, or LOW
 */
export type Task = {
  id: string;
  title: string;
  description: string;
  column: 'todo' | 'in_progress' | 'review' | 'done';
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
};
